### ISSUE TITLE
Does not load a file with a space in the name

### ISSUE THREAD

**Issue by NikMeDev** [nerdunit/androidsideloader#1]
Does not load a file with a space in the name. Possible solution is to force rename file before sideloading.

**Comment by nerdunit** [comment]
Hi, what do you mean, sideloading?

**Comment by nerdunit** [comment]
Sideloading an apk with a space works fine for me, also for obb's if you are talking about the user.json I fixed it in the latest release

**Comment by nerdunit** [comment]
The name does not matter, issue should be fixed in the latest version, if the issue is still present please open another issue and post the exact file name and path (like C:\Users\MyName\some folder\name of the.apk)
