### ISSUE TITLE
Quota reached for all mirrors ,exiting Application.

### ISSUE THREAD

**Issue by Blue863** [nerdunit/androidsideloader#101]
I've made a post about this error already and was told its about the servers im trying to connect to. How do I connect to a different server or launch in offline mode?

**Comment by frakman1** [comment]
I was able to get past this by placing the `rclone.conf` file in `/Users/myuser/.config/rclone` I obtained the file from the respective Telegram page. It keeps getting updated so better to use the one from there.
Anyway, I've included the one I used in case it helps for now.
Make sure you rename it to `rclone.conf` because Github won't let be upload a `.conf` file.
[rclone.txt](https://github.com/nerdunit/androidsideloader/files/7655008/rclone.txt)

**Comment by mambrino** [comment]
Hi,

I have the same problem here: quota reached for all mirrors, exiting application. Even using the latest .conf from the SideNoder telegram or the one attached by frakman1. I can't connect in any way.

**Comment by frakman1** [comment]
@mambrino: You just have to keep trying different mirros and remotes until you find one that works. Nothing will bypass a Google quota.

I had to try all these before I finally got a certain apk to download:

![image](https://user-images.githubusercontent.com/5826484/144750460-eccdebe7-12af-4a71-8aa3-68994709cd74.png)

**Comment by frakman1** [comment]
For me, the clue was when I looked at the log file: `debuglog.txt` and saw a message like this:
```
07:32PM(UTC): Running Rclone command: listremotes
07:32PM(UTC): Rclone error: 2021/12/04 19:32:42 NOTICE: Config file "C:\\Users\\myuser\\.config\\rclone\\rclone.conf" not found - using defaults
```
Maybe your error is different.
I confirmed that rclone can see the mirrors using either `rclone listremotes` or `rclone config`

Output looks like this:
```
c:\Users\myuser\Downloads\rclone>rclone listremotes
FFA-01:
FFA-02:
FFA-03:
FFA-04:
FFA-06:
VRP-mirror13:
VRP-mirror21:
VRP-mirror22:
VRP-mirror26:
VRP-mirror27:
VRP-mirror28:
VRP-mirror29:
VRP-mirror30:
VRP-mirror31:
VRP-mirror32:
VRP-mirror33:
VRP-mirror34:
VRP-mirror35:
VRP-mirror36:
VRP-mirror37:
VRP-mirror38:
VRP-mirror39:
VRP-mirror40:
VRP-mirror41:
VRP-mirror42:
VRP-mirror43:
VRP-mirror44:
```

I decided to just use a rclone gui like Rclone Browser and download the files manually and use `adb install -r <filename.apk>` to install the apps. I have a Mac so I used SideQuest to drag and drop the .obb folder into the filesystem of the Quest 2. There are probably other ways to do that too on Windows.

Hope that helps!

**Comment by mambrino** [comment]
Yes, it seems that there is some problem with sideloader, if I use rclone together with a browser it works perfectly.
It would be better to be able to do it with sideloader, but while this is solved it can help.

Thanks for the info ;)

**Comment by SytheZN** [comment]
There's nothing we can do about google's quotas unfortunately.
