### ISSUE TITLE
Feature Request: Connect to ADB Wifi

### ISSUE THREAD

**Issue by DocMAX** [nerdunit/androidsideloader#105]
I run the tool in a virtual machine where i cant connect via USB. But i allready enabled ADB Wifi elsewhere.
Can you add an option to just connect to a given ip/hostname?
That would be great!

**Comment by haruupi** [comment]
I need this, the IP query isn't working properly for me, so it would be a lot better if I could manually specify the IP or hostname of the device.

**Comment by Fenopy** [comment]
In C:/RSL/platform-tools/StoredIP.txt you may enter connect 0.0.0.0:5555
Replacing 0.0.0.0 with your quest ip. This will not bypass the required cable-authentication.
It isn't possible to authorize a device without connecting with a cable first.
