### ISSUE TITLE
Windows automaticcaly removes the app.

### ISSUE THREAD

**Issue by Tomaszito** [nerdunit/androidsideloader#106]
Windows automaticcaly removes the app. And i cant do anything about it i kill the windows defender and dont haVE ANTIVIRUS BUT WINDOWS KEEPS KILLING APP IMMEDIATELLY DELETE THE FILES.

**Comment by cscheerer** [comment]
Same

**Comment by SytheZN** [comment]
You do have an antivirus, it's called Windows Defender.

Google for how to add an exception.
