### ISSUE TITLE
Checking if config is updated and updating config...

### ISSUE THREAD

**Issue by ChaosCrafter908** [nerdunit/androidsideloader#107]
when launching the app it loads for eternity and cycles thru all mirrors... also had the "mirror quota reached " error but i "fixed" that

**Comment by DigiDexx** [comment]
> when launching the app it loads for eternity and cycles thru all mirrors... also had the "mirror quota reached " error but i "fixed" that

mind sharing how you "fixed" that?

**Comment by ChaosCrafter908** [comment]
> > when launching the app it loads for eternity and cycles thru all mirrors... also had the "mirror quota reached " error but i "fixed" that
> 
> mind sharing how you "fixed" that?


ofc, if you have that error then in the log it should say somewhere that rclone couldnt find a .conf file. go to that directory and paste [this](https://github.com/nerdunit/androidsideloader/files/8104569/rclone.txt) file in with the .conf file format

**Comment by DigiDexx** [comment]
ok so after applying the .conf, its actually checking the mirros first, then reporting "mirror quota reached". Whereas before, it would simply say that on launch without actually checking first

**Comment by ChaosCrafter908** [comment]
> ### [<img alt="@DigiDexx" width="20" height="20" src="https://avatars.githubusercontent.com/u/57231973?s=60&amp;u=16761ef677d967b4dc7843a08fe9c31c1a8cd86c&amp;v=4">](/DigiDexx) ** [DigiDexx](/DigiDexx) ** commented [vor 17 Minuten](#issuecomment-1046313311)

yea, ive just given up on Rookie launcher, i decided to go with FFLauncher, its WAYY better: get it here:: https://discord.gg/QvYwqvdgxc
