### ISSUE TITLE
Signing by apktool failed to install

### ISSUE THREAD

**Issue by FlashLim** [nerdunit/androidsideloader#11]
apktools version 2.4.1

Error while spoofing apk
install_parse_failed_no_certificates

Current workaround:
Generate my own keystore and sign it myself. Then sideload it manually. It works..

**Comment by nerdunit** [comment]
Generating a key works fine for me, what os are you using?

**Comment by nerdunit** [comment]
keystore generation is fixed in next updated, thanks!
