### ISSUE TITLE
Still No GAMES...

### ISSUE THREAD

**Issue by imJumsy** [nerdunit/androidsideloader#12]
i downloaded the newest version of sideloader and still no games, nothing's popping up. Is it just for me?

**Comment by ov3rk1ll** [comment]
Have you tried my suggestion from https://github.com/nerdunit/androidsideloader/issues/9#issuecomment-731076942?
Moving the file called "a" from the main folder to the "rclone" folder fix this issue for me.

If you don't have a file called "a", you have to find that someplace else as suggested [here](https://github.com/nerdunit/androidsideloader/issues/9#issuecomment-731558093).

**Comment by nerdunit** [comment]
> i downloaded the newest version of sideloader and still no games, nothing's popping up. Is it just for me?

you are missing the rclone config, you either make one yourself or get one already made.
