### ISSUE TITLE
cant connect to remote server 

### ISSUE THREAD

**Issue by MiraclGaming** [nerdunit/androidsideloader#125]
i loads it up and it pops up with it saying that and then 3 web sites

**Comment by Fenopy** [comment]
Can you confirm you are on the latest version?
Additionally, your PC must be able to reach Github, rclone.org, and Rookie cannot be blocked by your firewall.

**Comment by MiraclGaming** [comment]
yes

> Can you confirm you are on the latest version? Additionally, your PC must be able to reach Github, rclone.org, and Rookie cannot be blocked by your firewall.

yes 


> Can you confirm you are on the latest version? Additionally, your PC must be able to reach Github, rclone.org, and Rookie cannot be blocked by your firewall.

yes

**Comment by Fenopy** [comment]
I'd suggest asking for support in our Telegram or Discord. These are not application issues, but instead a local issue.
Thanks

**Comment by MiraclGaming** [comment]
I got it working

**Comment by RageTK0** [comment]
how did u get it working?
