### ISSUE TITLE
V2.16 Crash on Start

### ISSUE THREAD

**Issue by 503Dev** [nerdunit/androidsideloader#126]
Hello,

Using v2.16 portable on Win 11. Upon launching a black splash screen (just black no text, rectangular) appears and just hangs. Right clicking in task bar reveals "Splash (Unresponsive)". Force closing is the only way to proceed or does not ever load. 

v2.15 worked fine. Tried updating then also tried a fresh copy of the files from this GitHub. Happens everytime with 2.16.  No error is provided. No antivirus active, no firewall.

**Comment by SytheZN** [comment]
None of the startup logic was changed with the 2.16 release.
Haven't been able to reproduce this behavior on my side.

Could I ask you to get in touch on Telegram or Discord so we can troubleshoot a bit?

**Comment by 503Dev** [comment]
Sure will do!
