### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by wlhaan4u** [nerdunit/androidsideloader#135]
Is it possible to change the appearance of the interface because the trailer field is too small
like this:-
https://i.ibb.co/X4SvxBb/Untitled.png

And one time unmute option

**Comment by Chax1** [comment]
I don't understand what you mean by "the trailer field is too small", it works by streaming a youtube video, which you can maximize, it will then maximize to the size of Rookie.

**Comment by Chax1** [comment]
![image](https://user-images.githubusercontent.com/69131569/222166654-d3388dd7-3d01-447d-9cd5-28f44314fb2e.png)
