### ISSUE TITLE
Entitlement check failed for many games with Rookie sideloader

### ISSUE THREAD

**Issue by RHlNOMIN** [nerdunit/androidsideloader#145]
I came from FFAIO but sadly it was shut down. I have tried Rookie Sideloader but when I open the newly downloaded game, it says "Entitlement check failed" or it opens and crashes seconds after opening it. And that happens for most of the games. Why?

**Comment by Fenopy** [comment]
This is not an issue with the application.

**Comment by RHlNOMIN** [comment]
yes it is. the games aren't working
