### ISSUE TITLE
Crash on start : The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by mitjana** [nerdunit/androidsideloader#147]
Hello thanks for this software I would like to try it but it crash,
The folder is located at the root of my C: drive and excluded from windows defender, I don't have any other antivirus.
I a using Windows 10, it tried to run it as administrator.
When I open the executable I instantly have the AndroidSideload has stopped working.

Here is the crashlog : 

Date/Time of crash: Thursday, May 04 @ 01:24AM (UTC)
Message: The specified executable is not a valid application for this OS platform.
Data: System.Collections.ListDictionaryInternal
Source: System
TargetSite: Boolean StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)

Debuglog: 

12:55AM(UTC): Attempting to Update Public Config
12:55AM(UTC): Retrived updated config from: https://wiki.vrpirates.club/downloads/vrp-public.json
12:55AM(UTC): Public config updated successfully.
12:55AM(UTC): Running command: kill-server
12:55AM(UTC): Running command: devices

Tell me if you need more informations.

**Comment by Chax1** [comment]
Are you on 32 Bit or 64 Bit? 

https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d

**Comment by mitjana** [comment]
I am on 64 bit.Le 4 mai 2023 19:22, Chax ***@***.***> a écrit :
Are you on 32 Bit or 64 Bit?
https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d

**Comment by Chax1** [comment]
That's odd, try moving the Rookie folder to C:/RSL instead of just C:/

**Comment by mitjana** [comment]
It already was in a folder at the root. 
I attached a screenshot of the error and the executable location if it can helps.
![rsl](https://user-images.githubusercontent.com/17208687/236687119-7035132a-ef57-441a-8cf7-6181778d3b93.png)

**Comment by Chax1** [comment]
Could you upload the crashlog here?

**Comment by mitjana** [comment]
Sure but it's the same as my first message. 
[crashlog.txt](https://github.com/nerdunit/androidsideloader/files/11415546/crashlog.txt)

**Comment by Chax1** [comment]
Oh, wow, it really is...sigh, okay, try deleting the C:/RSL folder, and then try this version 
[rookie_2.19_portable_incl_rclone (1).zip](https://github.com/nerdunit/androidsideloader/files/11415552/rookie_2.19_portable_incl_rclone.1.zip)

**Comment by mitjana** [comment]
No more error, thanks you so much for your support and the work you do !!
