### ISSUE TITLE
Application does not startup if system language is set to Portuguese (First startup)

### ISSUE THREAD

**Issue by euwlo** [nerdunit/androidsideloader#15]
I have tried to execute the application on a Windows 10 with main language set to Brazilian Portuguese and it was not able to start.

Looking inside the folder in the debug file I noticed several non unicode characters, this could be what it was preventing to start.
After changing the system language to English the application was able to start successfully and keep working after changing the language back to Portuguese.

English Debug with working application:
[debugEN.txt](https://github.com/nerdunit/androidsideloader/files/5759612/debugEN.txt)

Portuguese Debug not starting application:
[debugPT.txt](https://github.com/nerdunit/androidsideloader/files/5759613/debugPT.txt)

**Comment by nerdunit** [comment]
Thank you! It is a known bug, code here is already fixing this and also the new version will fix this, so either compile for yourself or please wait for new version
