### ISSUE TITLE
Quest 2 not being detected

### ISSUE THREAD

**Issue by questidiot** [nerdunit/androidsideloader#154]
When I open the sideloaded, it doesn't send an ADB prompt to the Quest, and the mount button does nothing. It doesn't ow up in windows explorer, either. Works in sidequest, but I would like to use rookie.

**Comment by Fenopy** [comment]
this is not a rookie issue. verify you have installed drivers and enabled developer mode.
you should be able to complete the following command via command line at any time-

- cd c:/rsl/platform-tools
- adb devices

if you do not see your device listed, this is a driver/dev mode issue.
do not use git for support, use our channels (tg/discord)
