### ISSUE TITLE
Downloads Not Finishing

### ISSUE THREAD

**Issue by clxppedskyes** [nerdunit/androidsideloader#162]
My downloads will go to around 2s left then restart. Only on select games.

https://github.com/nerdunit/androidsideloader/assets/136361969/a76f90d7-9975-4d35-a1cb-323ec2cd324f

I have tried uninstalling and reinstalling and stuff like that idk what causes it to happen.

**Comment by Chax1** [comment]
This is not an issue with the program, the games are split into files and the progressbar is per file.
