### ISSUE TITLE
MALWARE

### ISSUE THREAD

**Issue by RageTK0** [nerdunit/androidsideloader#175]
when i first opened the sideloader it said that it was malware

**Comment by Fenopy** [comment]
That is why this is directly in the Readme

!IMPORTANT!

This app might get detected as malware, however both the sideloader and the sideloader launcher are open source. And obviously, it isn't.
See: https://www.virustotal.com/gui/file/46b6e24a03a6670dfbbde6e6f06caac05f2f9486115ef7bd77e0b568df7e5342/detection
