### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by RageTK0** [nerdunit/androidsideloader#176]
---------------------------
Unable to connect to Remote Server
---------------------------
Unable to connect to Remote Server. Rookie is unable to connect to our Servers.

First time launching Rookie? Please relaunch and try again.

Things you can try:
1) Move the Rookie directory (Folder containing AndroidSideloader.exe) into C:\RSL
2) Try changing your systems DNS to either Cloudflare/Google/OpenDNS
3) Try using a systemwide VPN like ProtonVPN
4) Sponsor a private server (https://vrpirates.wiki/en/Howto/sponsored-mirrors)

ive tried doing everything except doing a private server and i dont know what to do

**Comment by Fenopy** [comment]
This is not an application issue. Please use our Telegram or Discord for support.

**Comment by RageTK0** [comment]
whats the discord?

**Comment by prodwinrar** [comment]
jeez cant even answer the mans question

**Comment by Fenopy** [comment]
This git is no longer maintained.
