### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by prodwinrar** [nerdunit/androidsideloader#177]
pretty cool how when I scan this new file it says it has a trojan but the virus total link you give says its totally safe, and then when I scan a older download of rookie that I got a few months back that I didn't get from GitHub it says its totally safe 🤯instead of telling people every time that we are LITERALLY at the source code acting like most the people you are talking to have any idea about what the f*ck your yapping about... just explain to us why it says there's a trojan, I'm sure there is a very simple explanation and it would keep people from being skeptical 🤯🤯🤯🤯

**Comment by prodwinrar** [comment]
well yes not everyone knows about that shi*t, almost everyone is here just to get free games 😭 and i get that its not signed by a corporation license, this is all you had to say dawg. but im not sure if you read my whole comment, how come the old AND working rookie side loader exe file that i scanned didnt say the same sh*t, and how come the link that you give says its safe but then again when i scan the EXACT same file it says something different, oh and btw on the EXACT same virus scanner

**Comment by prodwinrar** [comment]
look honestly i couldnt give 2 fucks but if you could just give a simple explanation for everything im saying that might make someone believe you

**Comment by Chax1** [comment]
No offense but we really don't care if someone believes us, use the program, or don't, not a loss to us, lol.

**Comment by Fenopy** [comment]
Then drop the new file into TotalVirus again. Maybe take it upon yourself to check it on your own?
I gave you a pretty straight forward explanation, but you sound fairly uneducated, so I am unsure how else to explain it.
Here's the Source. Here's the Virus Scans. Here's why it might trigger a false positive. Scan it yourself if you want.
Beyond that, what do you want us to say?

**Comment by prodwinrar** [comment]
look at you, still not giving an explanation to the more important questions lol, and im uneducated. i think your just trying to avoid answering certain things 😭

**Comment by Fenopy** [comment]
I gave you an answer, multiple times.
I will also mention, this Git is super outdated, the source has moved, and the "Link to the same file" is an old release. You would know these things if you tried to scan it yourself and see the hash changed.
