### ISSUE TITLE
Certain games not downloading

### ISSUE THREAD

**Issue by Purpld** [nerdunit/androidsideloader#179]
Idk why but certain games are saying they downloaded successfully but won't show up on my quest (eg. The room VR dark matter pistol whip and crisis brigade and pistol whip 2 I have a quest 2 and have enough storage on both devices if you need screenshots I can provide

**Comment by Fenopy** [comment]
This repo is no longer maintained.
This is also not an application issue.
Please use the VRP Telegram, Discord, or Reddit for support
