### ISSUE TITLE
Version/date information of currently installed apps

### ISSUE THREAD

**Issue by darkfader** [nerdunit/androidsideloader#23]
## Summary
Show version/date information of currently installed apps.
### Basic example
Show more information in currently installed list.
- add version number.  optionally an installation date 
- show if there's an update available (optionally colored), based on version number, manifest or even a file timestamp.
- alternatively, write an installation log file somewhere so it can be checked manually. (other than debuglog.txt)
### Motivation
We can't easily see what could be updated to a newer version.

**Comment by nerdunit** [comment]
Working on it
