### ISSUE TITLE
Improve progress indicators

### ISSUE THREAD

**Issue by davwheat** [nerdunit/androidsideloader#24]
## Summary

Right now, it's hard to tell what's going on while sideloading, especially during the Installing/Spoofing phase.

### Basic example

ADB command files from remote could also contain comments which update the UI to state what step is in progress.

```
#! Removing old files/folders
adb shell rm /data/a/b/c
#! Pushing APK to device
adb push "xxx.apk" /data/local/tmp
#! Installing APK onto device
adb shell pm install /data/local/tmp/xxx.apk
```

### Motivation

I've thought that the sideloader was frozen in many cases when it was actually just mid-way through doing something.

**Comment by nerdunit** [comment]
I don't know how to do this without making the code way worse than it already is, if someone finds a way and teaches me or someone makes a pull request it will be added.
