### ISSUE TITLE
Check adb authorization before download

### ISSUE THREAD

**Issue by rcerrejon** [nerdunit/androidsideloader#25]
## Summary
Would be great if the sideloader checks the adb authorization before download and not before install.

### Motivation
Sometimes after wait for a download (maybe a big sized download) the sideloader checks the adb status when it tries to install the apk, would be great if the sideloader check that before the download or if the app checks at the beginning, opening the app, the adb status authorized or not, to save some time. Anyway after the download it's going to be installed, so, why not first check the auth?
Thanks

**Comment by nerdunit** [comment]
Should be called on sideloader start from the next version
