### ISSUE TITLE
File System errors config name contains invalid characters

### ISSUE THREAD

**Issue by AngelKing86** [nerdunit/androidsideloader#30]
I tested the new release and have the follwing problems

OS: Windows 10 Pro
Version: v2.0-WIP-SU from last release
Test-Folder: c:\temp\

Running Rclone command: cat ":Quest Games/GameList.txt"
Rclone error: Failed to create file system for ":Quest Games/GameList.txt": config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space

Running Rclone command: sync ":Quest Games/.meta/thumbnails" "C:\Temp\Sideloader\thumbnails"
Rclone error: Failed to create file system for ":Quest Games/.meta/thumbnails": config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space

Running Rclone command: sync ":Quest Games/.meta/notes" "C:\Temp\Sideloader\notes"
Rclone error: Failed to create file system for ":Quest Games/.meta/notes": config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space

**Comment by nerdunit** [comment]
You are missing a config
