### ISSUE TITLE
Shows the game may take over a day in hours to download

### ISSUE THREAD

**Issue by AGitBased** [nerdunit/androidsideloader#31]
So I was trying to download Pixel Ripped 1995, and it showed i had to wait 11-18 hours for it to finish. Please fix this!

**Comment by AGitBased** [comment]
PS. This happens when I try to download Beat Saber 1.13.0 too, is it only because I have purchased it?

**Comment by nerdunit** [comment]
You are talking about a custom config, I'm not able to help you with that, if they use google drive then you probably have some sort of restriction
