### ISSUE TITLE
Exception System.Collections.ListDictionaryInternal

### ISSUE THREAD

**Issue by ezar** [nerdunit/androidsideloader#34]
Data: System.Collections.ListDictionaryInternal
Source: AndroidSideloader
TargetSite: Void listappsbtn()

**Comment by nerdunit** [comment]
Post debuglog aswell

**Comment by tieorange** [comment]
Same for me:

![image](https://user-images.githubusercontent.com/3984517/126359280-c79d635a-a6ca-4a4b-bbcc-9bfbdc2290b8.png)


Crash Log:
`Date/Time of crash: Tuesday, July 20 @ 06:16PM (UTC)
Message: The system cannot find the file specified
Data: System.Collections.ListDictionaryInternal
Source: System
TargetSite: Boolean StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)`

Debug Log:
`06:16PM(UTC): 

##############
##############
##############

APP LAUNCH DATE/TIME: Tuesday, July 20 @ 06:16PM (UTC)

##############
##############
##############




06:16PM(UTC): Running commandkill-server
`

**Comment by harryeffinpotter** [comment]
This has been fixed on the latest version.
