### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by izerotti** [nerdunit/androidsideloader#35]
I have version 1.17SU1, it just crashes when I update it, tell me what to do about it?

**Comment by izerotti** [comment]
Running command shell df
Running command devices
List of devices attached
1WMHH843JV0484	device




Devices:
1WMHH843JV0484



Running command  -s 1WMHH843JV0484 shell df
Filesystem      1K-blocks      Used Available Use% Mounted on
tmpfs             2973384       712   2972672   1% /dev
tmpfs             2973384         0   2973384   0% /mnt
tmpfs             2973384         0   2973384   0% /apex
/dev/block/dm-4   1651800   1646604         0 100% /
/dev/block/dm-5    321296    320324         0 100% /vendor
/dev/block/dm-6 242680204 225489632  17059500  93% /data
/data/media     242680204 225489632  17059500  93% /storage/emulated



Downloading update from https://raw.githubusercontent.com/nerdunit/androidsideloader/releases/download/v2.0-WIP-SU/AndroidSideloader.exe to AndroidSideloader v2.0-WIP-SU.exe

**Comment by nerdunit** [comment]
This is because the use of new rclone, download 2.0 manually, new version updating should work fine
