### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Rutakate8** [nerdunit/androidsideloader#36]
[crashlog.txt](https://github.com/nerdunit/androidsideloader/files/6351616/crashlog.txt)
[debuglog.txt](https://github.com/nerdunit/androidsideloader/files/6351617/debuglog.txt)
![image](https://user-images.githubusercontent.com/82956933/115571222-792b3b00-a2c7-11eb-86fd-3325483cedcd.png)

**Comment by nerdunit** [comment]
Try to reinstall the sideloader, download the rclone and adb manually, reopen if it doesn't work
