### ISSUE TITLE
not loading mirriors hanging way too long

### ISSUE THREAD

**Issue by Dreagon719** [nerdunit/androidsideloader#37]
hello has any one have this problem i loaded up the new update 2.0 su and i get this "missing thumbnails and note database" but it takes a very long time and nothing is loading everything else picks up my oculus but the mount don't work plz help

**Comment by scarluc** [comment]
I have the same issue

**Comment by nerdunit** [comment]
You need to have a config for it to work, please reopen if there's an issue while you have a working config
