### ISSUE TITLE
when i click download and install game it said:"apk installation output: Performing Streamed Install"

### ISSUE THREAD

**Issue by PiesGier** [nerdunit/androidsideloader#43]

**Comment by PiesGier** [comment]
after that it just doesn't do anything

**Comment by InsaneSoftware** [comment]
check your debug log.. its VERY busy atm so try another mirror

In your log theres probaly: `Failed to open source object: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded`

**Comment by nerdunit** [comment]
It's not a sideloader issue but a quota issue from the mirror provider, closing
