### ISSUE TITLE
Crash on startup AndroidSideloader-v2.0-WIP-SU2

### ISSUE THREAD

**Issue by liwenjing93** [nerdunit/androidsideloader#44]
Hi everyone and Dev, AndroidSideloader-v2.0-WIP-SU2 crashed on start up. This is debuglog:

------------------------------------------- 
Running command shell input keyevent KEYCODE_WAKEUP

Running command shell df
Filesystem      1K-blocks     Used Available Use% Mounted on
tmpfs             2973384      732   2972652   1% /dev
tmpfs             2973384        0   2973384   0% /mnt
tmpfs             2973384        0   2973384   0% /apex
/dev/block/dm-4   1667768  1662528         0 100% /
/dev/block/dm-5    321816   320832         0 100% /vendor
/dev/block/dm-6  55247244 31163108  23976280  57% /data
/data/media      55247244 31163108  23976280  57% /storage/emulated

--> Another log is longer: https://notepad.pw/share/1mv5n6pr0

![image](https://user-images.githubusercontent.com/9654732/116645661-7b188c80-a9a0-11eb-8847-5f40cd91b163.png)

-------------------------------------------
My PC Specs:

![image](https://user-images.githubusercontent.com/9654732/116645637-6c31da00-a9a0-11eb-8c29-156ccf499b2c.png)

**Comment by liwenjing93** [comment]
I tried to run it on another Laptop, Windows 7 x64 and the problem is still there:

![Uploading image.png…]()

**Comment by Potatoexe-exe** [comment]
Same, what gpu do u run on and also ive ran this on 2 devices still encountered the problem

**Comment by pmow** [comment]
@Potatoexe-exe @liwenjing93 Please try and reproduce on current version.

**Comment by nerdunit** [comment]
I can see an update window, please try to use with latest version
