### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by djsyco** [nerdunit/androidsideloader#48]
i have downloaded AndroidSideloader.exe and load it up and cant get any game list on there i gone back to AndroidSideloader v1.18.2

**Comment by KillahB33** [comment]
Yeah same here, going back for me doesn't fix this so I guess I need to uninstall first then it will fix it. 
Rclone still loads the list though so it's something with this.

**Comment by pmow** [comment]
Unrelated to this software.
