### ISSUE TITLE
It doesn't copy obb files

### ISSUE THREAD

**Issue by dkgitdev** [nerdunit/androidsideloader#49]
Steps to reproduce:

Select game with obb files.
Try to install it.
Check `/sdcard/Android/obb` for the files

**Comment by pmow** [comment]
It does copy obb files with the steps.  You need to provide logs and provide some idea of error(s).

**Comment by dkgitdev** [comment]
I'm sure I'll be having logs by tomorrow, but beat saber (215, with all dlcs) and robo recall are affected. I have some people with the same issues with these genes, so could you please give me one more chance and check those?
I'll try to gather the logs, though

**Comment by dkgitdev** [comment]
And I think we can close this one -- I've reinstalled windows and it got working again, so I lost the opportunity to get the logs :(
