### ISSUE TITLE
Windows Defender "Fix"

### ISSUE THREAD

**Issue by teamcoltra** [nerdunit/androidsideloader#6]
Could we put the .exe into a zip or something in the releases? I am wondering if that will at least stop WD from blocking the download. I feel fairly competent and the level of hooplah I had to do to get WD to let me install this was crazy, just getting it downloaded in the first place was a pain.

Obviously that's part of the game in programs like this but also if we can find a more user friendly way to get it done that probably is useful to everyone.

**Comment by nerdunit** [comment]
It doesn't work that way, av's can scan zip files, I emailed microsoft once, they didn't fix it so if you want them to, report the file as a false positive
