### ISSUE TITLE
Dont use C Drive as temp folder

### ISSUE THREAD

**Issue by reloxx13** [nerdunit/androidsideloader#84]
There is a %TEMP% on window.
Or better stay in the folder the user selected to avoid trashing ssd´s, mounted ram disks or windows/os etc etc.

![grafik](https://user-images.githubusercontent.com/14855001/130788028-5c707ed4-7d57-497c-9898-afec2f5c0bc3.png)

And another

![grafik](https://user-images.githubusercontent.com/14855001/130788326-1500358d-0214-4d93-9c85-bb6bcc819345.png)

And another (on 2nd pc)
![grafik](https://user-images.githubusercontent.com/14855001/130788534-85165df9-b602-49b1-bc42-4146d6a41ed9.png)

**Comment by konqiDAM** [comment]
noted

**Comment by Fenopy** [comment]
These are no longer used, aside from c:/rsl for platform tools
