### ISSUE TITLE
Rookie's Sideloader 2.9.2 Update wont work.

### ISSUE THREAD

**Issue by DOOMswat** [nerdunit/androidsideloader#85]
![image](https://user-images.githubusercontent.com/89645506/131132372-58155c7d-4ffa-4552-8059-a42179f4589a.png)

When trying to update to 2.9.2 because there are no games on 2.1 available it detects it as unwanted software and deletes the new application in 30 seconds.

**Comment by BoyNG** [comment]
Same issues!
Windows antiviral protection display message about critical Trojan:Win32/Wacatac.B!ml

**Comment by pmow** [comment]
Remove any software that interferes with the operation of RSL and then the operation of RSL will not be interfered with.
