### ISSUE TITLE
I cant download games

### ISSUE THREAD

**Issue by imJumsy** [nerdunit/androidsideloader#9]
Rookie sideloader recongizes my oculus quest but there are no games to download from the lower slide, waht do i do? This happened after the update ;/

**Comment by faaaaq** [comment]
I am having the same issue.

**Comment by ov3rk1ll** [comment]
Are you guys running the latest v1.17SU1 version as well? I got the same issue since the update.

It seems like rclone looks for it's config (the "a" file) in the wrong location. After moving the "a" file to the "rclone" folder, everything loads again.

**Comment by imJumsy** [comment]
Yep, The same thing about rclone thingy ;(

**Comment by nerdunit** [comment]
Rookie's Sideloader uses configs to serve games, I did not make any config so you have to search for configs or to make them yourself.

**Comment by mathuresh95** [comment]
Try running the sideloader as admin. That worked for me.

**Comment by redouek** [comment]
> Are you guys running the latest v1.17SU1 version as well? I got the same issue since the update.
> 
> It seems like rclone looks for it's config (the "a" file) in the wrong location. After moving the "a" file to the "rclone" folder, everything loads again.

wich one is the "a" file? And wich folder is the rigth one?

**Comment by Fenopy** [comment]
This git is no longer maintained and this thread is 4 years old.
