### ISSUE TITLE
[Request] Allow pointing to a local drive for APK installs (instead of downloading)

### ISSUE THREAD

**Issue by Benjamin-Berger** [nerdunit/androidsideloader#95]
For the users that have Reslio, it would be nice to have the sideloader know that I already have the APK's downloaded.

Normally if I hit download and install game, the file will first be downloaded, and then installed onto the headset. The new functionality would check to see if the game file already exists in a local folder. If it does, install onto the headset. If not, download as normal then install. 

Would save time and bandwidth. Personally, it would also be nice not to have to find the file and drag and drop every time I wanted to update.

**Comment by KaladinDMP** [comment]
It already does this. The local folder it checks is the rookie folder. Plan accordingly.  A new feature might be to change which local folder it scans but what you're asking for already exists.

**Comment by pmow** [comment]
This would require a redesign of how Rookie operates.  Currently, it loads the game list from a supplied list of mirrors.

**Comment by Fenopy** [comment]
This functionality is available by utilizing a Local rclone configuration.
