### ISSUE TITLE
Quota reached for all mirrors, exiting aplication

### ISSUE THREAD

**Issue by CitizenWasHere** [nerdunit/androidsideloader#97]
With the newer versions of sideloader, I have encountered this one issue when opening the program, I'm currently using the 2.10.4 version of sideloader, is there anything I could do to fix this issue?

**Comment by fritkeoldo** [comment]
idk

**Comment by edgel0rd** [comment]
same issue here, pretty frustrating. How does one even run it in offline mode if closes itself immediately?

**Comment by pmow** [comment]
> same issue here, pretty frustrating. How does one even run it in offline mode if closes itself immediately?

--offline switch

**Comment by exitthehouse** [comment]
@pmow , can you please clarify how to run it offline? even when I disable my wifi it still shows the same error.

**Comment by pmow** [comment]
> @pmow , can you please clarify how to run it offline? even when I disable my wifi it still shows the same error.

You add the --offline switch to the app shortcut.

**Comment by joedado** [comment]
@pmow what does that mean what do i do to add it to a shortcut
