### ISSUE TITLE
Quota reached for all mirrors ,exiting Application. Try the offline mode instead...

### ISSUE THREAD

**Issue by Blue863** [nerdunit/androidsideloader#99]
Whenever I launch 2.10.4 of this app is crashes with that message every time. Fix?

**Comment by JosephThePower** [comment]
same bro

**Comment by Oculus19** [comment]
Same here... upgraded to Win11, worked once, since then this error is constant.

Any ideas how to solve?

**Comment by pmow** [comment]
This has nothing to do with the application and all to do with the servers you are trying to connect to.

**Comment by Blue863** [comment]
well how do i connect to different servers?
